### PR TITLE
Added aggregate styling for currency

### PR DESCRIPTION
**Pull request by eversteeg**
### Pull Request (PR) Dexels-ui-kit

**Jira link**:
*No issue*

**Description of the pull request**:
*- applied logic to have currency styling in footer*
*- in order ot do that, added props to TableInstance and ColumnInstance*

<br />

- [ ] New component? Did you add it to the library exports file `src/lib/index.ts`?
- [ ] New iconfont? Update `selection.json`, `iconfont.css` (mind the path part) and the values in `src/app/types.ts`?

<br />

### CODE REVIEW

**Comment by ayalalevinger** [comment]
But why did you add attributes id to table row, td etc? Does react-table asked that and does anything with these ids?

**Comment by eversteeg** [comment]
> But why did you add attributes id to table row, td etc? Does react-table asked that and does anything with these ids?

Nope, it was for debug purposes, so you can clearly see which div is which, because there a re quite a few.
I don't see a reason to not have them in place, that's why  I left them.

**Comment by ayalalevinger** [comment]
> > But why did you add attributes id to table row, td etc? Does react-table asked that and does anything with these ids?
> 
> Nope, it was for debug purposes, so you can clearly see which div is which, because there a re quite a few.
> I don't see a reason to not have them in place, that's why I left them.

I think an Id attribute to a DOM element should be unique within a page so for the table en header it is unique but for a row it isn't unique anymore

**Comment by eversteeg** [comment]
> > > But why did you add attributes id to table row, td etc? Does react-table asked that and does anything with these ids?
> > 
> > 
> > Nope, it was for debug purposes, so you can clearly see which div is which, because there a re quite a few.
> > I don't see a reason to not have them in place, that's why I left them.
> 
> I think an Id attribute to a DOM element should be unique within a page so for the table en header it is unique but for a row it isn't unique anymore. maybe it is better to use className
> 
> ids

Removed ids

**Review by ayalalevinger — APPROVED** [review]

**Pull request merged**
